### ISSUE TITLE
call parse in static this() result in: Program exited with code -11

### ISSUE THREAD

**Issue by mw66** [JackStouffer/date-parser#28]
```
#!/usr/bin/env dub
/+ dub.sdl:
dependency "dateparser" version="~>3.0.2"
+/

import std.stdio;
import std.datetime;
import dateparser;

shared static this() {
}

void main() {
  writeln(parse("2260-12-25"));
}
```

in main it's ok:
```
$ dub ab.d 
2260-Dec-25 00:00:00
```

But, if in static this:
```
shared static this() {
  writeln(parse("2260-12-25"));
}

void main() {
}

$ dub ab.d 
Program exited with code -11
```

**Comment by JackStouffer** [comment]
It's because dateparser uses a `static this()` block to initialize the default English parser info and `shared static this()` blocks are always run before any `static this()` blocks. 

I'd have to think about what the "correct" way to fix this is, as `shared static this()` should always be used in the context of multi-threaded data. I never intended the library to be used in that way. At the time (haven't been following recently) `shared` was very underdeveloped and I designed the functions to be always thread local.

You can work around this by initializing your own parser with the default information in the block.

```d
import std.stdio;
import std.datetime;
import dateparser;
import std.experimental.allocator.gc_allocator;

shared static this() {
    auto parser = new Parser!GCAllocator(new ParserInfo());
    writeln(parser.parse("2260-12-25"));
}

void main() {
}
```

**Comment by JackStouffer** [comment]
@mingwugmail Out of curiosity, why are you using `parse` in `shared static this`? Are you initializing multi-threaded data with the result?

**Comment by mw66** [comment]
Thanks for the quick reply.

Yes, I'm caching some calendar date (as immutable constants), which will be used by the multi-threaded program.

**Comment by JackStouffer** [comment]
I added a contract to check for a null pointer in the default parser with an explanation for a workaround.
